# Generated by Django 2.2.1 on 2019-06-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SMI', models.CharField(max_length=500)),
                ('smiID', models.CharField(max_length=100)),
            ],
        ),
    ]
